version: '3.9'

services:
  updater:
    build: .
    container_name: updater
    volumes:
      - .:/app
      - /Users/anne/Documents:/data
    working_dir: /app
    command: ["python", "updater.py"]
